version: '3.5'
services:
  portafolio_daniel:
      build:
        context: .
        dockerfile: Dockerfile
      image: docker.pkg.github.com/daka22/portafolio_daniel/portafolio:latest
      container_name: portafolio_daniel
      restart: always
      networks:
          - proxy
          - red_interna
networks:
    red_interna:
        driver: bridge
    proxy:
        driver: bridge
        name: proxy
        external: true
